name: Build Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:  
    name: Build & Create Release
    runs-on: windows-latest

    steps:    
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Run msbuild
        run: msbuild Pandora.sln /t:Build /p:Configuration=Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          # Artifact name
          name: PandorasBox.zip          
          path: Build\Pandora
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-preview
          release_name: Release v5
          body: Automated build from GitHub Actions
          draft: false
          prerelease: false
